### ISSUE TITLE
[question] Is it currently possible to convert FL Studio preset (.fst) files into LMMS preset (.xpf) file?

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [Sembiance/dexvert#26]
[In here](https://github.com/Sembiance/dexvert/blob/master/SUPPORTED.md) it seems like both file are supported, but when I try to convert them it gives me an error of 
```
Traceback (most recent call last):
  File "C:\Users\Ascend\Executables\DawVert-main\dawvert_ui.py", line 126, in run
    dawvert_core.parse_input(in_file, dv_core.config_data)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\objects\core.py", line 320, in parse_input
    plug_obj.parse(self.convproj_obj, in_file, dv_config)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\plugins\input\mi_flp.py", line 306, in parse
    flp_obj.read(input_file)
    ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\objects\file_proj\proj_flp.py", line 466, in read
    for event_id, event_data in format_flp_tlv.decode(song_data, chunk_obj.end): self.do_event(event_id, event_data)
                                                                                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ascend\Executables\DawVert-main\objects\file_proj\proj_flp.py", line 313, in do_event
    self.current_ch_obj.plugin.name = self.def_pluginname
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'plugin'
```
![image](https://github.com/user-attachments/assets/0b4123f7-86d4-4d0e-8782-c83195f5641d)

**Comment by Sembiance** [comment]
Neither of those files are supported by dexvert. The same extensions are used by other file formats. Additionally, even if they were supported, dexvert isn’t generally able to convert from one file format to another, rather only into a small handful of modern formats. Lastly, I have no idea what DawVert is.

**Comment by ImGGAAVVIINN** [comment]
I am so sorry, I opened too many tabs at the same time and posted the issue
at the wrong project :P
